### ISSUE TITLE
Add ssl support

### ISSUE THREAD

**Issue by usefulnoise** [interfasys/piwik-yourls#3]
Currently I can't connect to my piwik instance via ssl. Not sure if it's because I'm using a self signed cert. or because your plugin doesn't support https connection at all.

By the way you made my day with this plugin! ;-D
Many thanks!

**Comment by owcv** [comment]
My Piwik also runs under https, so that would be a great feature! ;-)

**Comment by 2020media** [comment]
Yes, me also. Being able to connect to piwik that runs under https would be very useful.

**Comment by oparoz** [comment]
I'll take a look, it's also important for me, but I didn't have any issues in the past, so it might be a certificate validation problem.

**Comment by oparoz** [comment]
I've created the dev branch for Yourls 1.7+ and had no problem connecting to a Piwik installation using a valid cert. Since we rely on the official PHP tracker file provided by Piwik, it may not be possible to easily fix this for people using self-signed certificates and I would highly recommend getting a free one since it will generate errors in the browser of visitors.
